title: Julia Neugarten
url: "https://julianeugarten.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Publications"
   link: "/publications/"
 - name: "Creative Writing"
   link: "/creativewriting/"
 - name: "Contact"
   link: "/contact/"

# nav:
#  - name: "About"
#    link: "/julianeugarten/"
#  - name: "Publications"
#    link: "/julianeugarten/publications/"
#  - name: "Creative Writing"
#    link: "/julianeugarten/creativewriting/"
#  - name: "Contact"
#    link: "/julianeugarten/contact/"
